# Generated by Django 4.2.7 on 2023-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlogins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logins',
            options={'verbose_name_plural': 'Logins'},
        ),
        migrations.AddField(
            model_name='logins',
            name='codes',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
