# Generated by Django 4.2.7 on 2023-11-30 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getlogins', '0002_alter_logins_options_logins_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
