# Generated by Django 4.2.7 on 2023-11-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getlogins', '0003_logins_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logins',
            options={},
        ),
        migrations.RemoveField(
            model_name='logins',
            name='user',
        ),
    ]
