# Generated by Django 4.2.7 on 2023-11-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlogins', '0004_alter_logins_options_remove_logins_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='codes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
