# Generated by Django 4.2.7 on 2023-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlogins', '0006_alter_logins_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logins',
            options={'verbose_name_plural': 'Logins'},
        ),
        migrations.AlterField(
            model_name='logins',
            name='codes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
